### ISSUE TITLE
Importing test library 'Debugger' failed: ValueError: invalid version number '3.2rc1'

### ISSUE THREAD

**Issue by grossvati** [Snooz82/robotframework-debugger#1]
Nachdem Update von Robot Framework auf die Version 3.2rc1 erhalte ich im Keyword 

```
Import Library     Debugger     break_on_fail=false
```

die Fehlermeldung

```
Importing test library 'Debugger' failed: ValueError: invalid version number '3.2rc1'
Traceback (most recent call last):
   File "D:\Python\Lib\site-packages\Debugger\__init__.py", line 23, in <module> from Debugger.DebuggerGui import DebuggerGui
   File "D:\Python\Lib\site-packages\Debugger\DebuggerGui.py", line 13, in <module>     
       HTML_ENABLED = StrictVersion(robot.__version__) >= StrictVersion('3.2a1')
   File "D:\Python\Lib\distutils\version.py", line 40, in __init__     self.parse(vstring)
   File "D:\Python\Lib\distutils\version.py", line 137, in parse     raise ValueError("invalid version number '%s'" % vstring)
```

**Comment by Snooz82** [comment]
solved with Robot 3.2 ;-)
