### ISSUE TITLE
Python 3.9.0 and RF 

### ISSUE THREAD

**Issue by GegX** [Snooz82/robotframework-debugger#3]
while trying to install robotframework-debugger I got the following error with tkinterhtml

~: python3 -m pip install robotframework-debugger
```
Collecting robotframework-debugger
  Downloading https://files.pythonhosted.org/packages/d6/ea/6569a5698414201cb4ade04989f6e1a579e6c744b9a5aa77b641c418a852/robotframework_debugger-0.1.4-py3-none-any.whl
Collecting robotframework>=3.1 (from robotframework-debugger)
  Using cached https://files.pythonhosted.org/packages/38/43/e03efaa547a3158f0745c5ea7f1eafebd69d46f2c9aece3a8ba21992adc9/robotframework-3.2.2-py2.py3-none-any.whl
Collecting tkinterhtml (from robotframework-debugger)
  Downloading https://files.pythonhosted.org/packages/37/be/86c2db091f663667686726aa7c45dc5fa198683b018986e6a5854006dbd7/tkinterhtml-0.7.zip (930kB)
    100% |████████████████████████████████| 931kB 1.9MB/s 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 376, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 412, in run_egg_info
    self.setup_py, self.name,
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/__init__.py", line 14, in <module>
    from setuptools.dist import Distribution, Feature
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/dist.py", line 24, in <module>
    from setuptools.depends import Require
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/depends.py", line 7, in <module>
    from .py33compat import Bytecode
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/py33compat.py", line 54, in <module>
    unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

tkinterhtml is untouched since Feb 27, 2016 https://pypi.org/project/tkinterhtml/#files
This issue might be tackled in https://github.com/pypa/setuptools/pull/1788

my params:
setuptools-50.3.2
python 3.9.0
pip 9.0.1

Edit: Talked to Snooz (Q4.2020)
A fast workaround could be:
One could use python 3.8 or fork the repo and exclude tkinterhtml (it is not essential) and install it with pip from source

**Comment by Snooz82** [comment]
tkinterhtml is removed from the current release. it was too buggy.
